project_id: 763531
preserve_hierarchy: 1
files:
  - source: /src/main/resources/assets/carpetskyadditions/lang/en_us.json
    dest: /translations.json
    translation: /src/main/resources/assets/carpetskyadditions/lang/%locale_with_underscore%.json
  - source: /src/main/resources/assets/carpetskyadditions/carpet/lang/en_us.json
    translation: /src/main/resources/assets/carpetskyadditions/carpet/lang/%locale_with_underscore%.json
    multilingual: 1
    dest: /carpet_translations.json
