project_id: 763545
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: 1
files:
  - source: /src/main/resources/assets/carpetskyadditions/lang/en_us.json
    translation: /src/main/resources/assets/carpetskyadditions/lang/%locale_with_underscore%.json
    dest: /translations.json
  - source: /src/main/resources/assets/carpetskyadditions/carpet/lang/en_us.json
    dest: /carpet_translations.json
    translation: /src/main/resources/assets/carpetskyadditions/carpet/lang/%locale_with_underscore%.json
